### ISSUE TITLE
The handlers are not RESTful

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/BlendingTutorial#1]
The URI `/PetList/Details?name={?}` is not RESTful. 

The rules for URIs in our apps have been agreed on in https://github.com/Starcounter/Guidelines/issues/9 and explained in https://starcounter.gitbooks.io/guidelines/content/uris.html

A RESTful URI would be: `/petlist/pets/{?}`

Same for:

`/MedicalRecordProvider?name={?}` -> `/medicalrecordprovider/patients/{?}`

**Comment by Mackiovello** [comment]
Fixed. Closing
